name: CI
on:
  workflow_dispatch: 
  push: 
    branches: main
    
jobs:
  build:
    runs-on: autotests
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: 20
        - name: Install
          run: npm install
        - name: Test
          run: npx wdio run ./wdio.conf.ts
        - uses: actions/upload-artifact@v4
          if: always()
          with:
            name: logs
            path: ./reports/timeline-reporter.html